# Generated by Django 3.2.18 on 2023-04-09 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.URLField()),
                ('cal_burned_per_min', models.FloatField()),
            ],
            options={
                'db_table': 'Exercise',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('carbs_per_serving', models.FloatField()),
                ('cal_per_serving', models.FloatField()),
                ('pro_per_serving', models.FloatField()),
                ('fat_per_serving', models.FloatField()),
            ],
            options={
                'db_table': 'Food',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='O', max_length=1)),
                ('dob', models.DateField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('weight', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('target_calorie_intake', models.FloatField(default=0)),
                ('target_calorie_burn', models.FloatField(default=0)),
                ('target_carbohydrate_intake', models.FloatField(default=0)),
                ('target_protein_intake', models.FloatField(default=0)),
                ('target_fat_intake', models.FloatField(default=0)),
                ('target_water_intake', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('waist', models.FloatField()),
                ('hip', models.FloatField()),
                ('bmi', models.FloatField()),
                ('waist_hip_ratio', models.FloatField()),
                ('waist_height_ratio', models.FloatField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fitness.profile')),
            ],
            options={
                'db_table': 'Measurements',
            },
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fitness.food')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fitness.profile')),
            ],
            options={
                'db_table': 'FoodLog',
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('duration', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fitness.exercise')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fitness.profile')),
            ],
            options={
                'db_table': 'ExerciseLog',
            },
        ),
    ]
